### ISSUE TITLE
LFS Hosting of Model Over Quota

### ISSUE THREAD

**Issue by ksmith54** [wdoppenberg/crater-detection#10]
Hi W.T.,

My name is Kyle Smith. I'm working on a crater navigation project at NASA's Johnson Space Center and came across your thesis in our search for crater detectors. The ellipse RCNN approach is very attractive us and we'd like to try it out in a framework that we're standing up to compare different models. 

When I went to clone your repo I'm seeing the following: 
```
Downloading blobs/CraterRCNN.pth (221 MB)
Error downloading object: blobs/CraterRCNN.pth (56d7d50): Smudge error: Error downloading blobs/CraterRCNN.pth  
(56d7d509074ca1bcc276dd7beb67910be8e78ed8dd885ebcebb9917b59528b96): batch response: This repository is over its data quota.  
Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Would you be willing to host the model on google drive or somewhere similar? 

Feel free to reach out over email (kyle.w.smith@nasa.gov) if you have questions about our project!

**Comment by enzosoft55** [comment]
Hello, 

my name is Vincenzo . I am student in Sapienza University in Rome, Italy and I also would like to receive the same file. Is it possible to have it via any means? 

THank you in advance and I am available to the following mail for any further information "prisco.2097261@studenti.uniroma1.it"

VP

**Comment by wdoppenberg** [comment]
Hi both. Very pleased to hear of your interest in this project. I currently do not have access to my laptop but I will attempt to provide you the model weights sometime next week.

Furthermore, if you're interested in setting up a training pipeline with some surface rendering software I'd love to help out.

**Comment by wdoppenberg** [comment]
@ksmith54 @enzosoft55 this should now be resolved. Please try fetching the files again

**Comment by ksmith54** [comment]
I was able to pull the repo, including the model weights, successfully. Thank you!
